### ISSUE TITLE
Cobudget 0.3

### ISSUE THREAD

**Issue by jonlemmon** [cobudget/cobudget-ui#115]
- [ ] Password reset
- [x] Admin is real
- [x] Group dropdown only shows your groups
- [x] Editable buckets
- [x] Invitations system #101
- [ ] Email about allocation #104

**Comment by derekrazo** [comment]
SO CLOSE! :dancer: :+1:  :100:  :8ball:

**Comment by getresults** [comment]
Yay! Great work!
