### ISSUE TITLE
Build failing on angular-bootstrap-datetimepicker

### ISSUE THREAD

**Issue by jonlemmon** [cobudget/cobudget-ui#183]
Getting this error on npm install:

```
npm ERR! Failed at the angular-bootstrap-datetimepicker@0.3.7 postinstall script './node_modules/bower/bin/bower install'.
```

I had to delete the line in the datepicker's package.json that tries to run bower to get it working.

**Comment by ahdinosaur** [comment]
was fixed, then unfixed, now waiting on https://github.com/dalelotts/angular-bootstrap-datetimepicker/pull/156.
