### ISSUE TITLE
implement logged-out password reset

### ISSUE THREAD

**Issue by ahdinosaur** [cobudget/cobudget-ui#194]
API implementation: https://github.com/open-app/cobudget-api/pull/65.

login flow:

1. see logged out page, can click on "Log In" to see login modal (2).
2. see login modal (ask for email and password), can click on "Log In" to see logged in page (3) or "Forgot Your Password?" to see forgot your password modal (4).
3. see logged in page, can click on "Log Out" to see logged out page (1).
4. see forgot your password modal (ask for email), can click on "Submit" to see reset confirmation modal
5. see reset confirmation modal, click "Okay" to see logged out page (1).
6. have forgot your password token, go to password reset modal. (7)
7. see password reset modal (ask for password twice), can click on "Submit" to see logged in page (3).

**Comment by derekrazo** [comment]
+1 

The only thing I would add here is that at #4 the user should get some indication / confirmation that the email has been sent.

**Comment by ahdinosaur** [comment]
good call, edited.

**Comment by ahdinosaur** [comment]
#checkin been taking longer than expected to push this feature out. :ocean: 

i'm realizing that if i want to feel motivated to work on Cobudget, i need to start feeling greater ownership of what i'm building here. i don't feel a motivating sense of ownership of the current stack, because it wasn't my decision to use Angular (back in the early days i wrote [a feature-parity (at the time) fork of Cobudget using React](https://github.com/ahdinosaur/cobudget-ui/tree/react), but yeah nah) and in fact The Angular Way is anti-thetical to my personal opinions on software development.

anyways, i've decided to start taking https://github.com/cobudget/cobudget-ui/issues/141 more seriously and do what i can to write new code in a way that feels good to me. to that end, since this feature requires heaps of modals i played around with modals using ampersand [here](https://github.com/cobudget/ampersand-modal-view) and [here](https://github.com/cobudget/cobudget-ui/tree/ampersand-modal). it ended up taking longer than expected feeling around with these ampersand modals, but i have learned heaps in the process that will make the transition to ampersand views realistic sooner rather than later.

in the end, i'm gonna push out this feature using Angular modals as before with a much needed refactor of our auth system using proper models (which are now ampersand models because of #193).

:lollipop:

**Comment by jonlemmon** [comment]
Good to hear your honest feedback Mikey. Personally I'm all for you taking more ownership over the tech stack. :)

**Comment by Dorotea** [comment]
Hi :-) not sure if it's a good place to ask/report bugs, but I'm trying to login to cobudget ( it usually takes quite a while, sometimes several attemps to even open the url )  I have cleared all the data in my browser and need to reset the password, but there is no option to do so ... pinged you on twitter about it too. Thanks!

**Comment by ahdinosaur** [comment]
hey @Dorotea, thanks for letting us know, we're happy to sort out your problem. i made a new issue to track this: https://github.com/cobudget/cobudget-ui/issues/250, let's continue over there.
