### ISSUE TITLE
no automatic cusror select

### ISSUE THREAD

**Issue by s01us** [cobudget/cobudget-ui#197]
when i click the fund button, I don't automatically get a cursor, so I have to click again.
I also don't get the text auto-selected, so i have to navigate around with arrow keys or delete manually rather than just starting to type and over-writing

If I try and double click on the box to select all the text it saves the box and closes editing 

![selection_117](https://cloud.githubusercontent.com/assets/2665886/6478453/37a4eb10-c298-11e4-99fe-9c7b77abf9ef.png)

---

```
Firefox 36.0, for Ubuntu canonical 1.0
Ubuntu 14.10
```

**Comment by derekrazo** [comment]
+1 to firefox love
ᐧ

**Comment by s01us** [comment]
gotta get of the google bra

**Comment by s01us** [comment]
.... bro ..

**Comment by derekrazo** [comment]
brew <--- NZFTFY
ᐧ

**Comment by ahdinosaur** [comment]
reproduced at http://www.browserstack.com/start#os=OS+X&os_version=Mountain+Lion&browser=Firefox&browser_version=36.0&zoom_to_fit=true&full_screen=true&url=http%3A%2F%2Fstaging.cobudget.co%2F&resolution=1280x1024&speed=1&host_ports=google.com%2C80%2C0, i think this has something to do with #196.
