### ISSUE TITLE
error: cannot transition to abstract state 

### ISSUE THREAD

**Issue by ahdinosaur** [cobudget/cobudget-ui#205]
> Hey guys, just tried to log into Cobudget and got this error message:    Error: Cannot transition to abstract state '[object Object]'
>   at Object.$.transitionTo (http://app.cobudget.co/scripts/index.js:5:3427)
>   at Object.$.reload (http://app.cobudget.co/scripts/index.js:5:2824)
>   at null.<anonymous> (http://app.cobudget.co/scripts/index.js:32:27044)
>   at h (http://app.cobudget.co/scripts/index.js:10:6653)
>   at r.trigger (http://app.cobudget.co/scripts/index.js:10:6000)
>   at http://app.cobudget.co/scripts/index.js:32:29319
>   at u (http://app.cobudget.co/scripts/index.js:7:26294)
>   at http://app.cobudget.co/scripts/index.js:7:26466
>   at f.$eval (http://app.cobudget.co/scripts/index.js:8:1543)
>   at f.$digest (http://app.cobudget.co/scripts/index.js:8:52)
>
> And now I'm in :simple_smile:

hmm... definitely due to our `ui-router` routes, not sure which route is the problem though.

**Comment by derekrazo** [comment]
![screenshot_2015-05-02-13-24-43](https://cloud.githubusercontent.com/assets/3849179/7485265/ec45846a-f3e6-11e4-9d20-c09f84c4a681.png)

This is turning out to be quite a common error. Here's a pic of another user's log.

**Comment by ahdinosaur** [comment]
how to reproduce:
- when not logged in, browse to some route, like [#/groups/1/rounds/26/buckets/181](http://app.cobudget.co/#/groups/1/rounds/26/buckets/181)
- login
- error!
- refresh page and it works fine

**Comment by ahdinosaur** [comment]
i think this is the line that's erroring: [app/controller.js#L44](https://github.com/cobudget/cobudget-ui/blob/master/src/node_modules/app/controller.js#L44)

**Comment by ahdinosaur** [comment]
deployed, seems to work.

**Comment by derekrazo** [comment]
Yaaaaay!! :)
