### ISSUE TITLE
unable to reset password

### ISSUE THREAD

**Issue by ahdinosaur** [cobudget/cobudget-ui#250]
from https://github.com/cobudget/cobudget-ui/issues/194#issuecomment-148226780,

@Dorotea says:

> Hi :-) ... I'm trying to login to cobudget ( it usually takes quite a while, sometimes several attemps to even open the url ) I have cleared all the data in my browser and need to reset the password, but there is no option to do so ... pinged you on twitter about it too. Thanks!

**Comment by ahdinosaur** [comment]
@Dorotea: is this for Alpha (<http://app.cobudget.co>) or Beta (<http://beta.cobudget.co>)?

**Comment by Dorotea** [comment]
beta

**Comment by ahdinosaur** [comment]
sweet. i notice there's a card for this on the project trello: [User can reset password from log-in screen](https://trello.com/c/x3wDo23b/16-user-can-reset-password-from-log-in-screen). ping @euglazer @derekrazo

**Comment by euglazer** [comment]
hi @Dorotea !

thx for submitting this issue :). i apologize for the long load times, we are in the process of rebuilding/refactoring the UI codebase (https://github.com/cobudget/cobudget-ui/pull/248) and should be done within 1 - 2 days. after the linked PR is merged in, page load should speed up significantly.

and yep, as @ahdinosaur, adding the ability to reset password is on the backlog, and we'll get to it as soon as we can.

in the meantime, feel free to email me at eugene@enspiral.com, and i can reset your password for you.

thx again!

**Comment by Dorotea** [comment]
Thank you! 
Let me know if I can help with more beta testing / proposing features / etc. Following your trello board for now.

**Comment by data-doge** [comment]
@Dorotea 

hey! only took a few months but this is done now :wink: 

https://github.com/cobudget/cobudget-ui/pull/278

![here's how](http://recordit.co/yeHKc1acAq.gif)
