### ISSUE TITLE
Input sanitation for non integer amounts

### ISSUE THREAD

**Issue by aShure** [cobudget/cobudget-ui#270]
Field turns green and submission possible if correct syntax entered, ie ``300``. Also turns green when ``300.42`` is entered, however no submission possible and no error message shown.

**Comment by data-doge** [comment]
@aShure is this still an issue? may have been fixed in https://github.com/cobudget/cobudget-ui/pull/269

**Comment by aShure** [comment]
Not fixed in #269 as of now: http://g.recordit.co/vNXEmDIl9d.gif

**Comment by data-doge** [comment]
closing -- we are only allowing integer contributions on buckets now
