### ISSUE TITLE
User should be able to change name, email, password (!!)

### ISSUE THREAD

**Issue by aShure** [cobudget/cobudget-ui#272]
At this beta stage now it is very important to have a function to change a password.

**Comment by data-doge** [comment]
hi @aShure. thx for the feedback + suggestions! tickets exist for the issues you've raised on our [sprint board](https://trello.com/b/Ca4BpYOz/cobudget-sprint-board). we're a small team (2 people primarily), and are running very lean, and are feeling pretty tired atm. after some rest, we'll be back on the grind again, and hopefully the issues you've raised will soon be resolved.

:)

**Comment by data-doge** [comment]
@aShure 

done -- see https://github.com/cobudget/cobudget-ui/pull/278

**Comment by data-doge** [comment]
though currently, we're leaving email as a disabled field.
