### ISSUE TITLE
Funded status time is the current time

### ISSUE THREAD

**Issue by NotThatSmith** [cobudget/cobudget-ui#316]
When viewing a bucket that is fully funded the date and time of funding is always the current date and time. I would expect this to be the date and time of when the bucket reached the goal.

When I refresh it updates.

![screenshot](https://cloud.githubusercontent.com/assets/1152577/15003571/318f0a26-1201-11e6-8ad8-dfa6a2b6cd8c.png)

http://beta.cobudget.co/#/buckets/271

**Comment by data-doge** [comment]
@NotThatSmith thx !!! issue resolved in https://github.com/cobudget/cobudget-ui/commit/be79a0631eb3fd29f69042f93018cfc1420c8b2f
