### ISSUE TITLE
Fix minification

### ISSUE THREAD

**Issue by kiesia** [cobudget/cobudget-ui#318]
@ahdinosaur mentioned on slack that minification was turned off because it caused an error in the javascript. 

Currently the gzipped size of index.js is 1.04MB. If we minify then that is reduced down to 369kB. So it's a good target for reducing app load time.

I'm no angular expert, does anyone want to work on this with me?

**Comment by kiesia** [comment]
The error I'm getting when I enable uglyifyify is:

```
Error: [$injector:modulerr] Failed to instantiate module cobudget due to:
[$injector:modulerr] Failed to instantiate module qAllSettled due to:
[$injector:unpr] Unknown provider: t
http://errors.angularjs.org/1.5.8/$injector/unpr?p0=t
t/<@http://localhost:9000/scripts/index.js:788:377
rt/x.$injector<@http://localhost:9000/scripts/index.js:788:21269
r@http://localhost:9000/scripts/index.js:788:20223
i@http://localhost:9000/scripts/index.js:788:20523
a@http://localhost:9000/scripts/index.js:788:20695
r@http://localhost:9000/scripts/index.js:788:19603
h/<@http://localhost:9000/scripts/index.js:788:19735
r@http://localhost:9000/scripts/index.js:788:823
h@http://localhost:9000/scripts/index.js:788:19512
h/<@http://localhost:9000/scripts/index.js:788:19681
r@http://localhost:9000/scripts/index.js:788:823
h@http://localhost:9000/scripts/index.js:788:19512
rt@http://localhost:9000/scripts/index.js:788:21441
ie/a@http://localhost:9000/scripts/index.js:788:8074
ie@http://localhost:9000/scripts/i
```

**Comment by kiesia** [comment]
@data-doge could this be a problem with https://www.npmjs.com/package/ng-q-all-settled?

**Comment by agentlewis** [comment]
@kiesia I cant reproduce this. By uncomenting the bundler in the [gulpfile.coffee](https://github.com/cobudget/cobudget-ui/blob/master/Gulpfile.coffee#L85)

i can run gulp scripts-build and get what looks like a minified output - ie 1.3mb. where does one turn on uglification?

**Comment by kiesia** [comment]
@agentlewis firstly I hadn't worked out how to turn the minification on, so I used an online service. Using gulp to do it, I get a file that's 1.24MB. I enabled it by uncommenting line 85 of gulp.coffee.

**Comment by kiesia** [comment]
Ah I see, this is a known bug with angular and uglifyjs: https://stackoverflow.com/questions/17238759/angular-module-minification-bug

Turning mangle off seems to fix it. ```bundler.transform(global: true, mangle: false, 'uglifyify')```. Then we get a 1.5MB index.js. How can I verify that the UI is working? Are there tests somewhere?

**Comment by data-doge** [comment]
@kiesia no UI tests, during development, the UI was in too much flux to justify ui-testing

best way to test would be to flick through a few of the pages, click on things, try signing up, signing in, signing out, creating a bucket, etc. locally. 

if you want, i can do some manual testing later today -- probably in about 2-3 hours i'll be free for a moment

**Comment by kiesia** [comment]
PR #319 here. I might have some time in 2-3 hours too.

**Comment by kiesia** [comment]
As far as I can tell by manually trying things out, this is working fine. If we add [ng-annotate](https://github.com/olov/ng-annotate) in the future then we can cut the file size down a lot further.

**Comment by kiesia** [comment]
Ah I see, we are using ng-annotate already, and it was falling over on the some external modules.
