### ISSUE TITLE
User option: currency

### ISSUE THREAD

**Issue by sdgluck** [cobudget/cobudget-ui#332]
It would be nice if the admin of a group could choose the currency that the group holds.

I wasn't sure if this should be an issue on `cobudget-api` or here, and I don't know what implications this would have, but in my mind all it requires is switching on some user option and displaying the correct currency symbol accordingly, hence why I am submitting to the UI repo.

**Comment by joshuavial** [comment]
@sdgluck an admin can set the currencies of the groups they manage by going to http://cobudget.co/#/admin - unfortunately the currencies are hardcoded in the app but pull requests for more currencies are welcome
